# Generated by Django 4.0.3 on 2022-03-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
