# Generated by Django 4.0.3 on 2022-04-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restfulApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_data',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('job_industry', models.CharField(max_length=100)),
                ('full_time', models.BooleanField()),
                ('min_average', models.FloatField()),
                ('max_average', models.FloatField()),
                ('average', models.FloatField()),
                ('approval_rate', models.FloatField()),
            ],
        ),
    ]
